default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Prinny13!

development:
  <<: *default
  database: lale_development
  <% if ENV["IsDockerContainer"] %>
  username: postgres
  host: 127.0.0.1
  <% end %>

test:
  <<: *default
  database: lale_test
  <% if ENV["IsDockerContainer"] %>
  username: postgres
  host: 127.0.0.1
  <% end %>
